### PR TITLE
Add summary, category, doc, website, bugs, repository; change descrip…

### PR DESCRIPTION
**Pull request by pmaier1**
…tion

Screenshot/cover image still missing. @hurradieweltgehtunter

### CODE REVIEW

**Comment by patrickjahns** [comment]
@pmaier1 
keep this open and include screenshot, or shall we have a separate PR for screenshot

**Comment by hurradieweltgehtunter** [comment]
Sorry guys, took me too long. Any opinions on that?
owncloud-app-email-template-editor

**Comment by hurradieweltgehtunter** [comment]
Update
owncloud-app-email-template-editor

**Comment by pmaier1** [comment]
Added the second screenshot. Ready to merge from my side.

**Pull request merged**
