### PR TITLE
Makefile and changelog

### PR DESCRIPTION
**Pull request by VicDeo**
Add changelog, copying, makefile, gitignore

### CODE REVIEW

**Comment by VicDeo** [comment]
@patrickjahns

**Comment by patrickjahns** [comment]
Since this is related to the release, can you please rebase against https://github.com/owncloud/templateeditor/tree/release/0.2.0

**Comment by VicDeo** [comment]
@patrickjahns I see no need to recreate makefile/changelog for every release.
So master should have these changes too.
Opened another PR against release/0.2.0 https://github.com/owncloud/templateeditor/pull/57

**Comment by patrickjahns** [comment]
@VicDeo 

During the conference, it was agreed to follow the "oneflow" for release branches - see here: http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow#starting-a-release-branch

You are correct, the makefile should not be create for every release. Yet once this release is ready, the changes from the release branch would flow back into the development branch (master). 

Adding/Updating the changelog is something that is finalized during the release process (when we started a release branch). The release will contain changes required to make a certain application release ready (this might include final fixes for bugs discovered during qa / and also changes to changelog/release scripts etc.) 

Sorry for the confusion / If the information was not communicated properly

**Comment by VicDeo** [comment]
closing then

**Pull request closed without merging**
