### PR TITLE
Wrong path to lost password template.

### PR DESCRIPTION
**Pull request by chriseqipe**
Fix wrong path to core template lostpassword.

### CODE REVIEW

**Comment by michaelstingl** [comment]
@MorrisJobke @butonic I don't see this fix in the [owncloud-9.0.2RC1.zip](http://download.owncloud.org/community/testing/owncloud-9.0.2RC1.zip). Will this be in the 9.0.2 release?

00005353

**Comment by MorrisJobke** [comment]
> @MorrisJobke @butonic I don't see this fix in the owncloud-9.0.2RC1.zip. Will this be in the 9.0.2 release?
> 
> 00005353

No. This then would need a backport to stable9.

cc @karlitschek Are you okay with the backport?

**Comment by MorrisJobke** [comment]
Was moved with 9.0 - https://github.com/owncloud/core/commit/d6a63016ae0e14efeefd763a1042c515b60b3f7d

**Comment by MorrisJobke** [comment]
I just noticed that I even fixed the path 3 months ago, but forgot to push the commit -.-

**Comment by MorrisJobke** [comment]
I prepared the backport https://github.com/owncloud/templateeditor/pull/43

**Comment by karlitschek** [comment]
yes. please backport 👍

**Pull request merged**
